version: 0.2

phases:
  pre_build:
    commands:
      # - echo "test phase started"
      # - npm test
      # - echo "test phase ended"
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - >
          REPOSITORY_URI_EXPRESS=830432741239.dkr.ecr.us-east-1.amazonaws.com/dispatch
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI_EXPRESS:latest .
      - docker tag $REPOSITORY_URI_EXPRESS:latest $REPOSITORY_URI_EXPRESS:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI_EXPRESS:latest
      - docker push $REPOSITORY_URI_EXPRESS:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"dispatch","imageUri":"%s"}]' $REPOSITORY_URI_EXPRESS:$IMAGE_TAG > imagedefinitions.json
      - echo All done now ...
artifacts:
    files: imagedefinitions.json

  # If using CodePipeline, imagedefinitions.json (the artifacts: files:) must
  # be inserted in the Staging stanza
