# If the node version is changed here, change it below as well
FROM node:10.7-stretch
# FROM node:10.7-stretch AS build

RUN apt-get update && apt-get install -y \
    awscli \
    libtool \
    vim-tiny \
    libssl-dev \
    autoconf \
    automake \
    git \
    pkg-config \
    python3-setuptools \
    python-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src
# WORKDIR /dispatch
RUN git clone https://github.com/facebook/watchman.git
RUN cd watchman && git checkout v4.9.0 && ./autogen.sh && ./configure && make && make install

RUN mkdir dist-dispatch
COPY src/assets/favicon.ico dist-dispatch/favicon.ico
COPY package.json .

# Set build env vars used in the docker build, not used on the server
ARG AWS_ACCESS_KEY_ID=AKIAJQAORV26GQCNYONA
ARG AWS_SECRET_ACCESS_KEY=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
ARG AWS_REGION=us-east-1

# Update with a fresh set of environment variables
# and aws-exports for Cognito
RUN aws s3 cp s3://dispatchresponse/scripts/environment-vars.txt .env
RUN aws s3 cp s3://dispatchresponse/scripts/aws-exports.js .aws-exports.js

# Install dependencies
# RUN npm install --production
RUN npm install

# FROM node:10.7-stretch
# FROM node:10.7-slim
# WORKDIR /usr/src
# COPY --from=build /dispach .

# Ensure we have the system set to the correct timezone
ENV TZ 'America/New_York'
RUN echo $TZ > /etc/timezone && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean

ENV NODE_ENV=production

# WORKDIR /usr/src
ADD . .

RUN npm run build
RUN rm -rf watchman

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
